-- Step 1: Create Schemas
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'corp')
    EXEC('CREATE SCHEMA corp');
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'assoc')
    EXEC('CREATE SCHEMA assoc');
GO

-- Step 2: Relocate Corporate Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Tenants')
    ALTER SCHEMA corp TRANSFER dbo.Tenants;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Associations')
    ALTER SCHEMA corp TRANSFER dbo.Associations;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'SubscriptionPlans')
    ALTER SCHEMA corp TRANSFER dbo.SubscriptionPlans;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'AssociationSubscriptions')
    ALTER SCHEMA corp TRANSFER dbo.AssociationSubscriptions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'AuditLogs')
    ALTER SCHEMA corp TRANSFER dbo.AuditLogs;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'RefreshTokens')
    ALTER SCHEMA corp TRANSFER dbo.RefreshTokens;

-- Step 3: Relocate Association Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Assets')
    ALTER SCHEMA assoc TRANSFER dbo.Assets;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Persons')
    ALTER SCHEMA assoc TRANSFER dbo.Persons;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Occupancy')
    ALTER SCHEMA assoc TRANSFER dbo.Occupancy;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Vehicles')
    ALTER SCHEMA assoc TRANSFER dbo.Vehicles;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Pets')
    ALTER SCHEMA assoc TRANSFER dbo.Pets;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Invoices')
    ALTER SCHEMA assoc TRANSFER dbo.Invoices;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Payments')
    ALTER SCHEMA assoc TRANSFER dbo.Payments;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Transactions')
    ALTER SCHEMA assoc TRANSFER dbo.Transactions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'WorkOrders')
    ALTER SCHEMA assoc TRANSFER dbo.WorkOrders;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Broadcasts')
    ALTER SCHEMA assoc TRANSFER dbo.Broadcasts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TariffGroups')
    ALTER SCHEMA assoc TRANSFER dbo.TariffGroups;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TariffLayers')
    ALTER SCHEMA assoc TRANSFER dbo.TariffLayers;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'AssetTariffs')
    ALTER SCHEMA assoc TRANSFER dbo.AssetTariffs;

-- Step 4: Split Users and Roles (Logical Separation)
-- For now, we will move the main Users table to corp, but we will create association-specific roles in assoc.
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users')
    ALTER SCHEMA corp TRANSFER dbo.Users;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'UserAssociations')
    ALTER SCHEMA corp TRANSFER dbo.UserAssociations;

-- We will keep Identity tables (if any) in dbo or move them to corp as well.
GO
